//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2011 - Infos @ http://www.17buddies.net //
//          More than 60000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by Christmas Server for 17Buddies.
//
// Map Name  : cs_christmas_legend
//
// Download @: http://www.17buddies.net/17b2/View/Map/25066/cs_christmas_legend.html
//
//////////////////////////////////////////////////////////
// Wad files legend:
//     *  : Hardcoded in bsp file, this wad was found (in
//          archive or on 17Buddies's website) but doesn't
//          contains any used texture.
//          However, this file may be necessary.
//     ** : Hardcoded in bsp file, this wad could not be
//          found (neither in archive nor on 17Buddies's
//          website) and thus could not be analysed.
//          However, this file may be necessary.
//////////////////////////////////////////////////////////
// cs_christmas_legend.wad (**)
gfx/env/havup.tga
gfx/env/havdn.tga
gfx/env/havlf.tga
gfx/env/havrt.tga
gfx/env/havft.tga
gfx/env/havbk.tga
// models/cs_christmas_legend/stul2.mdl
// models/cs_christmas_legend/bottle_beer.mdl
// models/cs_christmas_legend/bowl_ramen.mdl
// models/cs_christmas_legend/shower.mdl
// models/cs_christmas_legend/couch_leather-black.mdl
// models/cs_christmas_legend/coat_rack.mdl
// models/cs_christmas_legend/trash_trashcan.mdl
// models/cs_christmas_legend/micro.mdl
// models/cs_christmas_legend/coffee_maker.mdl
// models/cs_christmas_legend/coffee_props-can.mdl
// models/cs_christmas_legend/coffee_props-sugar.mdl
// models/cs_christmas_legend/maniak_milk.mdl
// models/cs_christmas_legend/sink_small.mdl
// models/cs_christmas_legend/bathroom_toilet.mdl
// models/cs_christmas_legend/chair_leather.mdl
// models/cs_christmas_legend/pc.mdl
// models/cs_christmas_legend/telefon.mdl
// models/cs_christmas_legend/inbox.mdl
// models/cs_christmas_legend/chair_office.mdl
// models/cs_christmas_legend/lip_cabinet_dark.mdl
// models/cs_christmas_legend/Xen_refr2.mdl
// models/cs_christmas_legend/trash03.mdl
// models/cs_christmas_legend/crs_sh_b.mdl
// models/cs_christmas_legend/crs_sh_g.mdl
// models/cs_christmas_legend/crs_sh_r.mdl
// models/cs_christmas_legend/crs_sh_y.mdl
// models/cs_christmas_legend/lamp12.mdl
// models/cs_christmas_legend/e4g1e_tv.mdl
// models/cs_christmas_legend/zentr.mdl
// models/cs_christmas_legend/scr_lamp_3_glass.mdl
// models/cs_christmas_legend/tablelamp.mdl
// models/hostage.mdl
// models/cs_christmas_legend/snow_car1.mdl
// models/cs_christmas_legend/($z)EJIKA2.mdl
// models/cs_christmas_legend/($z)CHEgOBuk.mdl
// models/cs_christmas_legend/lamp_street-euro2.mdl
// models/cs_christmas_legend/lamp_street-euro2a.mdl
// sound/cs_christmas_legend/george_michael_-_last_christmas.wav
