//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_austria
//
// Download @: http://dwl.17buddies.net/link/map/8080/de_austria.html
//
//////////////////////////////////////////////////////////
de_austria.wad
gfx/env/austriaup.tga
gfx/env/austriadn.tga
gfx/env/austrialf.tga
gfx/env/austriart.tga
gfx/env/austriaft.tga
gfx/env/austriabk.tga
models/woodgibs.mdl
models/metalgibs.mdl
models/lv_bottle.mdl
models/winebottle.mdl
models/de_austria_models/apfel.mdl
models/de_austria_models/charles.mdl
models/de_austria_models/souther.mdl
 
sound/de_austria_sounds/hurz_mono_kurz.wav  
sound/de_austria_sounds/explode4.wav
sound/de_austria_sounds/auto_boom.wav
sound/de_austria_sounds/tree_kkrrrr.wav
sound/de_austria_sounds/tree_fall.wav
sound/ambience/waterrun.wav
sound/ambience/drips.wav
sound/ambience/crow.wav
sound/ambience/cat1.wav
sound/ambience/dog5.wav
sound/ambience/burning1.wav
 
sprites/de_austria_sprites/Takeshi.spr
sprites/de_austria_sprites/austria_explo1.spr
sprites/de_austria_sprites/austria_explo2.spr
sprites/de_austria_sprites/austria_glow.spr
sprites/de_austria_sprites/austria_fire.spr 
sprites/de_austria_sprites/ORION.spr
sprites/wsplash3.spr
sprites/smoke.spr 
sprites/flare1.spr 
sprites/sdrip1.spr
 