snowy_winter.wad
gfx/env/backalleyup.tga
gfx/env/backalleydn.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyft.tga
gfx/env/backalleybk.tga
models/medion/christmas/streetlight2.mdl
sprites/glow01.spr
models/medion/christmas/wallLight.mdl
models/medion/christmas/fireplace_logs1.mdl
sprites/medion/jx0firesmall.spr
models/medion/christmas/candle.mdl
models/medion/christmas/santaSock.mdl
models/medion/christmas/venok.mdl
models/medion/christmas/venokWall.mdl
models/medion/christmas/lustra2.mdl
models/medion/christmas/table03.mdl
models/medion/christmas/bush52.mdl
models/medion/christmas/bush49.mdl
models/medion/christmas/bush56.mdl
models/medion/christmas/couch_leather-black.mdl
models/medion/christmas/3dm_tafel.mdl
models/pred_plant.mdl
models/medion/christmas/trees_plane.mdl
models/medion/christmas/tides_light_fixture.mdl
models/medion/christmas/dead_tree03.mdl
models/medion/christmas/skla_nissan.mdl
sprites/medion/hotel.spr
models/player/guerilla/guerilla.mdl
models/player/gsg9/gsg9.mdl
models/medion/christmas/jolkabig.mdl
models/medion/christmas/jolkaStreet.mdl
sprites/medion/ledsSanta.spr
models/medion/christmas/jolka.mdl
models/medion/christmas/SWAT_VAN.mdl
sprites/medion/santastar.spr
models/medion/christmas/van1_1.mdl
sound/medion/nightwind.wav
